### ISSUE TITLE
更换数据集后loss下降越来越慢的问题

### ISSUE THREAD

**Issue by mengya22** [Diamondfan/CTC_pytorch#1]
我更换了数据集来用ctc做视频识别对齐问题，但总体的框架是用您的代码来训练，当我更换了数据集之后，ctcloss下降的越来越慢，请问根据您的经验有什么方法可以解决么
![image](https://user-images.githubusercontent.com/30148082/31488013-ff036c84-af6e-11e7-8da9-
![qq 20171012170209](https://user-images.githubusercontent.com/30148082/31488051-1be7248a-af6f-11e7-99bf-fe8a2c662324.png)

**Comment by Diamondfan** [comment]
我不太了解视频识别对齐任务。但是可以从两个角度分析：
1、超参数问题，比如初始学习率设置的太小了，不适合这个任务，导致开始loss下降缓慢
2、特征的分类能力不足，就是特征或者标签的选择不好，导致输出可能分不开
