### ISSUE TITLE
Decode wav file into phonemes?

### ISSUE THREAD

**Issue by Terrance82** [Diamondfan/CTC_pytorch#2]
Hi,
I'm interested in your project however I'm new in Speech recognition etc. 
I want to know if your program able to convert from wav audio files and detect its phoneme?

If so, how do i proceed on doing so?
Thank you

**Comment by Diamondfan** [comment]
@Terrance82  The project can only convert wav files to phoneme with an offline mode. It means you have to extract features in advance and get some ark files. Then run test.py to get phoneme sequence after you train a model with enough data.
