### ISSUE TITLE
dev dataset

### ISSUE THREAD

**Issue by coolcoolhua** [Diamondfan/CTC_pytorch#6]
在做数据准备的时候没法找到dev数据集。请问TIMIT是有多个版本吗？

**Comment by Diamondfan** [comment]
test目录下划分了验证集和测试集，根据conf/dev_spk.list 选择出验证集。详见：
https://github.com/Diamondfan/CTC_pytorch/blob/master/timit/local/timit_data_prep.sh#L42

**Comment by coolcoolhua** [comment]
> test目录下划分了验证集和测试集，根据conf/dev_spk.list 选择出验证集。详见：
> https://github.com/Diamondfan/CTC_pytorch/blob/master/timit/local/timit_data_prep.sh#L42

我明白了 好像是因为TIMIT本身字母大小写导致的 31行的位置有覆盖 所以能正确找到
